universe = vanilla

Executable = /cephfs/users/gohdenze/micromamba/envs/TransientLightcurves/bin/python
initialdir = /cephfs/users/gohdenze/TransientSimulation

Arguments = job.py --N_tot 10 --batch 0 --output_dir /cephfs/users/gohdenze/TransientSimulation/results

Log    = /cephfs/users/gohdenze/TransientSimulation/LOGS/log_$(Cluster)_$(Process).log
Output = /cephfs/users/gohdenze/TransientSimulation/output/out_$(Cluster)_$(Process).txt
Error  = /cephfs/users/gohdenze/TransientSimulation/output/err_$(Cluster)_$(Process).txt

should_transfer_files = no

# request 2GB RAM
request_memory = 2048

queue 1